# https://docs.docker.com/compose/intro/compose-application-model/#key-commands
services:
  localstack:
    image: localstack/localstack
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - GATEWAY_LISTEN=0.0.0.0:4566
      - SERVICES=s3,dynamodb
    ports:
      - 4566:4566
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./.volume:/var/lib/localstack"