#https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
#https://docs.github.com/en/actions/how-tos/writing-workflows/choosing-when-your-workflow-runs/triggering-a-workflow?versionId=free-pro-team%40latest&productId=actions
name: Draft API CI/CD Pipeline

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
  #to enable manual triggering
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/Checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Initialize LocalStack
      run: |
        docker-compose -f docker-compose.test.yml up -d
        sleep 10

    - name: Run tests
      run: |
        python -m pytest tests/ -v

    - name: Cleanup
      run: |
        docker-compose -f docker-compose.test.yml down